apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: helloworld
  template:
    metadata:
      labels:
        app: helloworld
    spec:
      containers:
        - name: helloworld
          image: alpine:latest
          command: ["/bin/sh", "-c"]
          args:
            - echo "Hello, World!";
              while true; do sleep 3600; done
